---
# ... Service YAML definition
apiVersion: v1
kind: Service
metadata:
  name: clover
  labels:
    app: clover
spec:
  selector:
    app: clover
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
  type: LoadBalancer

---
# ... Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clover
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clover
  template:
    metadata:
      labels:
        app: clover
    spec:
      containers:
        - name: clover
          image: clover:latest
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              #             Your local ip address a.k.a where you started redis
              value: "192.168.0.140"
            #             redis port i.e default is 6379
            - name: REDIS_PORT
              value: "6379"
            - name: NODE_ENV
              value: development
          imagePullPolicy: Never
